const { getBuffer } = require('../../start/lib/myfunction');
async function dareCommand(kelvin, quoted, from, m) {
    const dares = [
        "Eat 2 tablespoons of rice without any side dishes.",
        "Spill a secret about yourself.",
        "Call your crush now and send a screenshot.",
        "Drop only emojis for 1 day in group chats.",
        "Sing the chorus of your favorite song.",
        "Change your name to 'I'm a daredevil' for 24 hours.",
        "Tell a random person 'I was told I'm your twin, separated at birth.'",
        "Pretend to be possessed by an animal for 30 minutes.",
        "Record yourself reading a funny quote and send it here.",
        "Prank chat an ex and say 'I still love you.'",
        "Change your profile picture to a funny meme for 5 hours.",
        "Type only in Spanish for 24 hours.",
        "Use a funny voice note greeting for 3 days.",
        "Drop a song quote and tag a suitable member.",
        "Say 'You're beautiful' to someone you admire.",
        "Act like a chicken in front of your parents.",
        "Read a page from a random book aloud and send it here.",
        "Howl like a wolf for 10 seconds outside.",
        "Make a short dance video and put it on your status.",
        "Eat a raw piece of garlic.",
        "Show the last five people you texted and what the messages said.",
        "Put your full name on status for 5 hours.",
        "Make a twerk dance video and put it on your status.",
        "Call your bestie and say 'I love you.'",
        "Put your photo without filters on your status.",
        "Say 'I love you' to someone you secretly admire.",
        "Send a voice note saying 'Can I call you baby?'",
        "Change your name to 'I'm a daredevil' for 24 hours.",
        "Use a Bollywood actor's photo as your profile picture.",
        "Put your crush's photo on status with the caption 'My crush.'",
        "Write 'I love you' to someone and send a screenshot.",
        "Slap your butt and send the sound effect.",
        "Shout 'Bravo!' and send it here.",
        "Snap your face and send it here.",
        "Send your photo with the caption 'I'm feeling confident.'",
        "Kiss your mom or dad and say 'I love you.'",
        "Put your dad's name on status for 5 hours.",
        "Make a TikTok dance challenge video.",
        "Break up with your best friend for 5 hours without telling them.",
        "Tell a friend you love them and want to marry them.",
        // Additional dares
        "Do 20 push-ups right now and send a video.",
        "Speak in a British accent for the next 10 messages.",
        "Text your mom 'I'm pregnant' then quickly say 'JK!'",
        "Wear your clothes backwards for 1 hour.",
        "Eat a spoonful of hot sauce.",
        "Call a random number and sing 'Happy Birthday'.",
        "Post an embarrassing childhood photo on your status.",
        "Let the group choose your WhatsApp status for 24 hours.",
        "Talk only in rhymes for the next 30 minutes.",
        "Do the floss dance in a public place.",
        "Wear socks on your hands for the rest of the day.",
        "Text your crush 'I dreamt about you last night'.",
        "Put ice cubes down your shirt and don't remove them for 2 minutes.",
        "Speak like a robot for the next 5 messages.",
        "Eat a banana without using your hands.",
        "Send the last photo in your gallery to the group.",
        "Talk to your pet (or a stuffed animal) for 5 minutes about your day.",
        "Wear a funny hat for the next 3 hours.",
        "Text your boss 'Good morning, sunshine!'",
        "Try to lick your elbow and send a picture.",
        "Speak in a different language for the next 10 minutes.",
        "Do the chicken dance in front of a mirror.",
        "Send a voice message singing 'Baby Shark'.",
        "Put on a fake mustache and take a selfie.",
        "Try to do a handstand against a wall.",
        "Send a screenshot of your most recent search history.",
        "Talk in a whisper for the next 15 minutes.",
        "Wear your shoes on the wrong feet for 1 hour.",
        "Send a compliment to the person you last texted.",
        "Try to touch your nose with your tongue.",
        "Speak in a movie villain voice for the next 5 messages.",
        "Send a voice note of you trying to beatbox.",
        "Wear a towel as a cape for 30 minutes.",
        "Text a friend 'Emergency! Send chocolate!'",
        "Try to spin around 10 times without getting dizzy.",
        "Send a photo of what's directly to your left.",
        "Talk like a pirate for the next 10 minutes.",
        "Attempt to juggle with 3 random objects.",
        "Send a screenshot of your battery percentage.",
        "Wear sunglasses indoors for 2 hours.",
        "Text your sibling 'You're my favorite person'.",
        "Try to balance a spoon on your nose.",
        "Send a voice message of you laughing hysterically.",
        "Walk backwards for the next 10 steps you take.",
        "Text your dad 'I need dating advice'.",
        "Try to say the alphabet backwards.",
        "Send a photo of your current view.",
        "Talk in a high-pitched voice for the next 5 messages.",
        "Attempt to do the splits (be careful!).",
        "Text your teacher/professor 'I really enjoyed class today!'",
        "Try to whistle your favorite song.",
        "Send a photo of your current outfit.",
        "Talk like a baby for the next 3 minutes.",
        "Do 10 jumping jacks right now.",
        "Text your neighbor 'Can I borrow some sugar?'",
        "Try to make the weirdest face possible and send a selfie.",
        "Send a screenshot of your home screen.",
        "Talk in slow motion for the next 5 messages.",
        "Wear something inside out for the rest of the day.",
        "Text a friend 'I have a secret to tell you... just kidding!'",
        "Try to write your name with your non-dominant hand and send a picture."
    ];

    const dareMessage = dares[Math.floor(Math.random() * dares.length)];
    
    try {
        const buffer = await getBuffer('https://i.ibb.co/305yt26/bf84f20635dedd5dde31e7e5b6983ae9.jpg');
        
        await kelvin.sendMessage(
            from,
            {
                image: buffer,
                caption: `🎯 *DARE CHALLENGE*\n\n${dareMessage}\n\n_You have 24 hours to complete this dare!_`,
            },
            { quoted: m }
        );
    } catch (error) {
        // If image fails, send text only
        await kelvin.sendMessage(
            from,
            {
                text: `🎯 *DARE CHALLENGE*\n\n${dareMessage}\n\n_You have 24 hours to complete this dare!_`,
            },
            { quoted: m }
        );
    }
}

async function truthCommand(kelvin, from, m) {
    const truths = [
        "What's your biggest fear?",
        "Have you ever lied to your best friend?",
        "What's your deepest secret?",
        "Who's your secret crush?",
        "What's the biggest mistake you've ever made?",
        "Have you ever cheated on a test?",
        "What's the most embarrassing thing that's ever happened to you?",
        "Do you have a hidden talent?",
        "What's the biggest lie you've ever told?",
        "Have you ever been in love?",
        "What's the most spontaneous thing you've ever done?",
        "Who's the person you trust most?",
        "What's the biggest risk you've ever taken?",
        "Have you ever regretted something?",
        "What's the most memorable gift you've received?",
        "Have you ever had a crush on someone older?",
        "What's the biggest lesson you've learned?",
        "Have you ever broken someone's heart?",
        "What's the most exciting thing you've done?",
        "Do you believe in soulmates?",
        "What's the biggest challenge you've faced?",
        "Have you ever kept a secret from your parents?",
        "What's the most creative thing you've done?",
        "Have you ever felt betrayed?",
        "What's the biggest adventure you've been on?",
        "Have you ever had a rival?",
        "What's the most thoughtful thing someone's done for you?",
        "Have you ever forgiven someone?",
        "What's the biggest obstacle you've overcome?",
        "Do you believe in karma?",
        "What's the most romantic thing someone's done for you?",
        "Have you ever taken a risk for love?",
        "What's the biggest surprise you've ever received?",
        "Have you ever had a paranormal experience?",
        "What's the most inspiring story you've heard?",
        "Have you ever helped someone in need?",
        "What's the biggest accomplishment you're proud of?",
        // Additional truths
        "What's something you've never told anyone about your childhood?",
        "Have you ever stolen something?",
        "What's your most irrational fear?",
        "Have you ever pretended to be sick to avoid something?",
        "What's the worst thing you've ever said to someone?",
        "Have you ever had a crush on a friend's partner?",
        "What's a habit you're ashamed of?",
        "Have you ever read someone else's diary or messages?",
        "What's the most selfish thing you've ever done?",
        "Have you ever cheated in a relationship?",
        "What's something you regret not doing?",
        "Have you ever lied to get out of trouble?",
        "What's the biggest amount of money you've ever wasted?",
        "Have you ever been fired or expelled?",
        "What's the most offensive joke you've ever laughed at?",
        "Have you ever pretended to like something to impress someone?",
        "What's your most controversial opinion?",
        "Have you ever ghosted someone?",
        "What's something you judge people for but do yourself?",
        "Have you ever had a secret relationship?",
        "What's the most hurtful thing someone has said to you?",
        "Have you ever spread a rumor?",
        "What's a promise you've broken?",
        "Have you ever pretended to be someone else online?",
        "What's the most embarrassing thing in your search history?",
        "Have you ever been attracted to someone you shouldn't be?",
        "What's something you've done while drunk/high that you regret?",
        "Have you ever taken credit for someone else's work?",
        "What's the biggest age gap you'd date?",
        "Have you ever snooped through someone's phone?",
        "What's something you've faked expertise in?",
        "Have you ever been arrested or detained?",
        "What's your biggest insecurity?",
        "Have you ever had a one-night stand?",
        "What's the most illegal thing you've done?",
        "Have you ever been in love with two people at once?",
        "What's something you've done that would shock your family?",
        "Have you ever manipulated someone to get what you wanted?",
        "What's your guilty pleasure?",
        "Have you ever had a crush on a teacher/professor?",
        "What's the most embarrassing thing you've done for attention?",
        "Have you ever been jealous of a friend's success?",
        "What's a secret you're keeping from your current partner?",
        "Have you ever had a crush on a celebrity?",
        "What's something you pretend to dislike but actually love?",
        "Have you ever been bullied or been a bully?",
        "What's the most hypocritical thing you do?",
        "Have you ever been in a physical fight?",
        "What's something you've done that you hope no one finds out about?",
        "Have you ever had feelings for a friend's sibling?",
        "What's the most amount of money you've found and kept?",
        "Have you ever pretended not to see someone to avoid them?",
        "What's your biggest regret in a past relationship?",
        "Have you ever kissed someone and immediately regretted it?",
        "What's something you've done that goes against your values?",
        "Have you ever had a secret social media account?",
        "What's the worst advice you've ever given?",
        "Have you ever been so angry you broke something?",
        "What's something you've lied about on your resume?",
        "Have you ever been attracted to someone much older/younger?",
        "What's the most embarrassing thing you've posted online?",
        "Have you ever betrayed a friend's trust?",
        "What's something you would never admit in public?",
        "Have you ever had a crush on your boss/manager?",
        "What's the biggest risk you took that failed?",
        "Have you ever been caught in a lie?",
        "What's something you've stolen from a friend's house?",
        "Have you ever had a secret job or side hustle?",
        "What's the most childish thing you still do?",
        "Have you ever faked an illness for sympathy?",
        "What's something you're embarrassed to enjoy?",
        "Have you ever been attracted to someone based on their wealth?",
        "What's the most embarrassing nickname you've had?",
        "Have you ever pretended to be wealthy?",
        "What's something you've done that you can't believe you did?",
        "Have you ever had a crush on a coworker/classmate you shouldn't?",
        "What's the most embarrassing gift you've ever given?",
        "Have you ever been secretly happy about someone else's misfortune?"
    ];

    const truthMessage = truths[Math.floor(Math.random() * truths.length)];
    
    try {
        const buffer = await getBuffer('https://i.ibb.co/305yt26/bf84f20635dedd5dde31e7e5b6983ae9.jpg');
        
        await kelvin.sendMessage(
            from,
            {
                image: buffer,
                caption: `💤*TRUTH OR DARE*\n\n${truthMessage}\n\n_Be honest! No lying allowed!_`,
            },
            { quoted: m }
        );
    } catch (error) {
        // If image fails, send text only
        await kelvin.sendMessage(
            from,
            {
                text: `💤 *TRUTH OR DARE*\n\n${truthMessage}\n\n_Be honest! No lying allowed!_`,
            },
            { quoted: m }
        );
    }
}

module.exports = {
dareCommand,
truthCommand
};